apiVersion: v1
kind: Secret
metadata:
  name: smtp-relay-credentials
  namespace: default
type: Opaque
stringData:
  user: "user@gmail.com"        # substitua pelo seu endereço Gmail
  password: "your-password"    # pode ser senha de app
