---
apiVersion: v1
kind: Namespace
metadata:
  name: smtp-relay
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smtp-relay
  namespace: smtp-relay
  labels:
    app: smtp-relay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smtp-relay
  template:
    metadata:
      labels:
        app: smtp-relay
    spec:
      containers:
        - name: smtp-relay
          image: gersontpc/smtp-relay:v1.0.0  # ajuste para o seu repositório
          ports:
            - name: smtp
              containerPort: 25
          env:
            - name: RELAY_USER
              valueFrom:
                secretKeyRef:
                  name: smtp-relay-credentials
                  key: user
            - name: RELAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: smtp-relay-credentials
                  key: password
            - name: MYDOMAIN
              value: "smtp-relay.smtp-relay.svc.cluster.local"
          startupProbe:
            exec:
              command:
                - sh
                - -ec
                - postfix status
            failureThreshold: 30
            periodSeconds: 2
            timeoutSeconds: 3
          readinessProbe:
            exec:
              command:
                - bash
                - -ec
                - exec 3<>/dev/tcp/127.0.0.1/25; exec 3>&- 3<&-
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            exec:
              command:
                - sh
                - -ec
                - postfix status
            periodSeconds: 30
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          # recursos e segurança adicionais podem ser definidos aqui
---
apiVersion: v1
kind: Service
metadata:
  name: smtp-relay
  namespace: smtp-relay
  labels:
    app: smtp-relay
spec:
  selector:
    app: smtp-relay
  ports:
    - protocol: TCP
      port: 25
      targetPort: 25
  type: ClusterIP
---
apiVersion: v1
kind: Secret
metadata:
  name: smtp-relay-credentials
  namespace: smtp-relay
type: Opaque
stringData:
  user: "<email>@gmail.com"        # substitua pelo seu endereço Gmail
  password: "<senha>"    # pode ser senha de app
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-smtp-from-app-ns-custom
  namespace: smtp-relay
spec:
  podSelector:
    matchLabels:
      app: smtp-relay
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: app-ns-custom
      ports:
        - protocol: TCP
          port: 25